version: "3.8"
services:
  nginx:
    container_name: nginx
    image: library/nginx:1.19-alpine
    ports:
      - 8080:80
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - ./src:/var/www/html
    depends_on:
      - mysql
      - redis
      - php

  php:
    container_name: php
    build: .
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=laraveldb
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel-test
      - MYSQL_ROOT_PASSWORD=laravel-test
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql

  redis:
    image: redis:6.0
    ports:
      - 6379:6379
