on:
  push:
    tags:
      - "*"

name: 🚀 Build Docker images on Tag created
jobs:
  build:
    name: 🎉 Build Docker images
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --working-dir src --profile --ignore-platform-reqs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ngnix Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: ghcr.io/lanyastudio/checkinlite-nginx:${{ github.ref_name }}

      - name: PHP-FPM Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.php
          push: true
          tags: ghcr.io/lanyastudio/checkinlite-php:${{ github.ref_name }}

  deploy:
    name: Deploy to Nomad
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Tigger deploy workflow
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.DEPLOY_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/LanyaStudio/nomad-jobs/dispatches \
            --data '{"event_type": "checkinlite-laravel", "client_payload": { "version": "${{ github.ref_name }}" }}'
